### ISSUE TITLE
Menus are displaying errors on click action

### ISSUE THREAD

**Issue by IceroDev** [NetHeberg/NetPanel-desktop#1]
![Capture d’écran du 2021-01-09 19-59-11](https://user-images.githubusercontent.com/69088819/104106356-50051280-52b5-11eb-8cd8-17411f1ac08c.png)

**Comment by IceroDev** [comment]
Issue seems to be a simple panel timeout. Closing issue

**Comment by stereo18** [comment]
To solve this :
- Click on "NetPanel" as top
- Go back on your server
